---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sciety--staging
  namespace: sciety
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-www-to-non-www@kubernetescrd
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: sciety--staging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sciety
spec:
  ingressClassName: traefik
  rules:
    - host: staging.sciety.org
      http:
        paths:
          - backend:
              service:
                name: sciety--staging--frontend
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - staging.sciety.org
        - www.staging.sciety.org
      secretName: sciety--staging--frontend--letsencrypt-cert
